FROM python:3.10

WORKDIR /usr/src/app

RUN apt-get update

COPY . .

RUN python -m pip install --upgrade pip && pip3 install -r requirements.txt

CMD [ "python3", "-m" , "flask", "run", "--host=0.0.0.0"]
